CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY, 
  username VARCHAR(50) NOT NULL UNIQUE, 
  email VARCHAR(50) NOT NULL UNIQUE,
  password_hashed TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

) 


CREATE TABLE IF NOT EXISTS todos (
  id SERIAL PRIMARY KEY, 
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE, 
  title VARCHAR(100) NOT NULL, 
  description TEXT,
  is_completed BOOLEAN DEFAULT FALSE,
  due_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);